#insert funcionario
INSERT INTO funcionario (funcionario_nome) VALUES
 ('André Luiz Tannus Dutra');

INSERT INTO funcionario (funcionario_nome) VALUES
 ('Andréa Fragata');

INSERT INTO funcionario (funcionario_nome) VALUES
 ('Antônio Estanislau Sanche');

INSERT INTO funcionario (funcionario_nome) VALUES
 ('Cássio Bernardes');

INSERT INTO funcionario (funcionario_nome) VALUES
 ('Charles Luiz Silva de Melo');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Clairon Lima Pinheiro');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Cláudio Gonçalves');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Cleinaldo de Almeida Costa');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Cleto Cavalcante de Souza Leal');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Cristine Alcântara Teixeira');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Danielle Noronha');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Eduardo Rafael Barreda del Campo');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Elisabete Brocki');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Emanuel Rezende Rodrigues');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Fabian Litaiff');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Felicien Gonçalvez Vasquez');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Gilberto Garcia del Pino');

INSERT INTO funcionario VALUES
 ('Hélio Braz');

INSERT INTO funcionario VALUES
 ('Ingrid Gadelha');

INSERT INTO funcionario VALUES
 ('Jamile Dehaini');

INSERT INTO funcionario VALUES
 ('João da Mata Libório Filho');

INSERT INTO funcionario VALUES
 ('Jorge Brito');

INSERT INTO funcionario VALUES
 ('Jorge Procópio Costa Novo');

INSERT INTO funcionario VALUES
 ('José Augusto Veiga');

INSERT INTO funcionario VALUES
 ('José Luiz');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Jozias Parente de Oliveira');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Jucimar Maia da Silva Júnior');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Luciano Balbino dos Santos');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Márcia Ribeiro Maduro');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Mário Augusto Bessa de F.');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Nadja Polyana Felizola Cabete');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Odwald Schreder');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Orlem Pinheiro lima');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Raimundo Correa de Oliveira');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Ricardo Wilson Aguiar da Cruz');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Roberto Higino Pereira da Silva');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Rubelmar Maia de Azevedo Cruz Filho');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Samara Barbosa de Menezes');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Sérgio Duvoisin Júnior');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Ubirajara Ferreira da Silva');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Walter Velenzuela');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Ana Carolina');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Anderson Nascimento de Sá');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Araci Freitas');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Conceição Brito');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Eliane Rodrigues Morais');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Jeane Monteiro Fernandes');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Joelma Carvalho');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Lizete Amazonas da Silva');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Lucilene Maciel');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Robson Almeida');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Ruan Paulo Amorim');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Sandy Bandeira Rebelo');

INSERT INTO funcionario(funcionario_nome) VALUES
 ('Willem da Silva Almeida');
